### ISSUE TITLE
oneClassNN

### ISSUE THREAD

**Issue by davidshih17** [raghavchalapathy/oc-nn_old#1]
I tried to run the jupyter notebook and encountered this error in tflearn_OneClass_NN_model.py:

----> 8 from tflearn.layers.estimator import regression, oneClassNN
....
ImportError: cannot import name 'oneClassNN'

Indeed, I do not find this layer anywhere in tflearn (or searching for it via google for that matter). Where can I obtain the code for oneClassNN?

**Comment by raghavchalapathy** [comment]
Please comment the import you should be fine , the oc-nn is entirely implemented in tensorflow- code 
if you follow for example function func_getDecision_Scores_synthetic , you will be able to figure out the implementation of oc-nn
