### ISSUE TITLE
customLoss error

### ISSUE THREAD

**Issue by jun20061588** [raghavchalapathy/oc-nn_old#3]
I run  the code ,but error. It is from keras.losses import customLoss, ImportError: cannot import name 'customLoss', what is it?

**Comment by keshasha** [comment]
I am not the author, but It looks like being able to remove.
Nowhere 'customLoss' is used.

**Comment by kefitk** [comment]
Hi.
I have the same issue. An error related to keras.losses. 
How did you fix it please?
